
services:
  app:
    image: todo-app:local
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:14-alpine
    container_name: todo-psql
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5